// ReadingTests.cs
// Part 1 (Monday). Some of these pass on the starter. The ones that fail
// describe the lockdown you are about to do. Do not edit this file.

using System.Reflection;
using Line3.Monitor;

namespace Line3.Monitor.Tests;

public class ReadingTests
{
    [Fact]
    public void P1_01_a_reading_keeps_what_it_was_given()
    {
        var reading = new Reading("oven-temp", 212.4, 7);
        Assert.Equal("oven-temp", reading.SensorId);
        Assert.Equal(212.4, reading.Value);
        Assert.Equal(7, reading.Sequence);
        Assert.False(reading.IsMissing);
    }

    [Fact]
    public void P1_02_a_missing_value_is_allowed_and_says_so()
    {
        var reading = new Reading("oven-temp", null, 8);
        Assert.Null(reading.Value);
        Assert.True(reading.IsMissing);
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void P1_03_a_blank_sensor_id_is_refused(string id)
    {
        Assert.ThrowsAny<ArgumentException>(() => new Reading(id, 212.4, 1));
    }

    [Theory]
    [InlineData(double.NaN)]
    [InlineData(double.NegativeInfinity)]
    public void P1_04_a_value_that_is_not_a_measurement_is_refused(double bad)
    {
        Assert.ThrowsAny<ArgumentException>(() => new Reading("oven-temp", bad, 1));
    }

    [Fact]
    public void P1_05_a_negative_sequence_is_refused()
    {
        Assert.ThrowsAny<ArgumentException>(() => new Reading("oven-temp", 212.4, -1));
    }

    [Fact]
    public void P1_06_no_public_fields()
    {
        string[] fields = typeof(Reading)
            .GetFields(BindingFlags.Public | BindingFlags.Instance)
            .Select(f => f.Name)
            .ToArray();
        Assert.Empty(fields);
    }

    [Fact]
    public void P1_07_no_public_setters()
    {
        string[] settable = typeof(Reading)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.SetMethod is { IsPublic: true })
            .Select(p => p.Name)
            .ToArray();
        Assert.Empty(settable);
    }
}
