# collection_timer.py
# Lab U01-04, Part 2, step 14. Do not edit this file.
#
# WorkCell keeps its machines in a dictionary keyed by asset tag. This script
# builds the same cell two ways, once with that dictionary and once with a
# plain list that is scanned for every add and every lookup, and times both.
#
#     python collection_timer.py
#
# Your times will differ from your neighbor's. The ratio is the point.

import sys
import time
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

from line3 import Machine, WorkCell  # noqa: E402

MACHINES = 3000


class ListCell:
    """The same job as WorkCell, with a list. Every add and get scans it."""

    def __init__(self, name):
        self.name = name
        self._machines = []

    def add(self, machine):
        for existing in self._machines:
            if existing.asset_tag == machine.asset_tag:
                raise ValueError(f"{machine.asset_tag} is already in cell {self.name}")
        self._machines.append(machine)
        return machine

    def get(self, asset_tag):
        for machine in self._machines:
            if machine.asset_tag == asset_tag:
                return machine
        return None


def build_machines():
    # 3000 different invented tags, L3-AAA-00 through L3-CJJ-09. Each digit of
    # the machine number becomes one letter or the last digit.
    machines = []
    for number in range(MACHINES):
        letters = "ABCD"[number // 1000] + "ABCDEFGHIJ"[number // 100 % 10] + "ABCDEFGHIJ"[number // 10 % 10]
        machines.append(Machine(f"L3-{letters}-{number % 10:02d}", f"Machine {number}", rated_kw=5))
    return machines


def time_cell(cell, machines):
    start = time.perf_counter()
    for machine in machines:
        cell.add(machine)
    for machine in machines:
        cell.get(machine.asset_tag)
    return time.perf_counter() - start


def main():
    machines = build_machines()
    dict_seconds = time_cell(WorkCell("Dictionary cell"), machines)
    list_seconds = time_cell(ListCell("List cell"), machines)
    print(f"{MACHINES} adds and {MACHINES} lookups")
    print(f"  dictionary (WorkCell): {dict_seconds:.4f} s")
    print(f"  list, scanned:         {list_seconds:.4f} s")
    if dict_seconds > 0:
        print(f"  the list took about {list_seconds / dict_seconds:.0f} times as long")


if __name__ == "__main__":
    main()
