# mutant_check.py
# Lab U01-04, Part 2. Do not edit this file, and do not edit line3/.
#
# A test suite that passes proves very little until you know it can fail.
# This script plants one bug at a time in a temporary copy of line3/, a
# "mutant", and runs your test_line3.py against it. If at least one of your
# tests fails, your suite CAUGHT that mutant. If every test still passes,
# the bug would have shipped.
#
#     python mutant_check.py
#
# Your real line3/ folder is never changed. Each mutant lives in a temporary
# folder that is deleted afterwards.

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
TEST_FILE = "test_line3.py"

# (name, file inside line3/, exact text to find, replacement)
MUTANTS = [
    ("M1 a duplicate asset tag is accepted",
     "cell.py",
     "        if machine.asset_tag in self._machines:\n",
     "        if False:\n"),
    ("M2 a running machine can be removed from the cell",
     "cell.py",
     "        if machine.is_running:\n",
     "        if False:\n"),
    ("M3 cell.machines hands out the real dictionary",
     "cell.py",
     "        return tuple(self._machines.values())\n",
     "        return self._machines\n"),
    ("M4 anyone can release a lockout",
     "machine.py",
     "        if badge != self.__lockout_holder:\n",
     "        if badge is None:\n"),
    ("M5 a NaN temperature is accepted",
     "machine.py",
     "        if not math.isfinite(value) or not Machine.MIN_TEMP_C <= value <= Machine.MAX_TEMP_C:\n",
     "        if value < Machine.MIN_TEMP_C or value > Machine.MAX_TEMP_C:\n"),
]


def run_tests(folder):
    """Run the student's tests in folder. Return (passed, number of tests, last line)."""
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    result = subprocess.run([sys.executable, "-m", "unittest", "test_line3"], cwd=folder, env=env,
                            capture_output=True, text=True, timeout=120)
    output = result.stderr + result.stdout
    ran = re.search(r"Ran (\d+) tests?", output)
    count = int(ran.group(1)) if ran else 0
    lines = [line for line in output.strip().splitlines() if line.strip()]
    return result.returncode == 0, count, (lines[-1] if lines else "no output")


def copy_project(destination):
    shutil.copytree(HERE / "line3", destination / "line3",
                    ignore=shutil.ignore_patterns("__pycache__"))
    shutil.copy2(HERE / TEST_FILE, destination / TEST_FILE)


def main():
    if not (HERE / TEST_FILE).is_file() or not (HERE / "line3").is_dir():
        print(f"Run this from the lab folder that holds {TEST_FILE} and line3/.")
        return 2

    with tempfile.TemporaryDirectory() as temp:
        clean = Path(temp) / "clean"
        clean.mkdir()
        copy_project(clean)
        passed, count, last = run_tests(clean)
    if not passed:
        print(f"Your tests FAIL on the real classes ({last}).")
        print("A test that fails on correct code is a wrong test. Fix it first:")
        print("    python -m unittest -v test_line3")
        return 1
    print(f"Your tests pass on the real classes. Tests run: {count}")
    print()

    caught = 0
    for name, filename, find, replace in MUTANTS:
        with tempfile.TemporaryDirectory() as temp:
            folder = Path(temp)
            copy_project(folder)
            target = folder / "line3" / filename
            source = target.read_text(encoding="utf-8")
            if source.count(find) != 1:
                print(f"{name}: could not be planted. Restore line3/ from the lab files.")
                continue
            target.write_text(source.replace(find, replace), encoding="utf-8")
            mutant_passed, _, _ = run_tests(folder)
        if mutant_passed:
            print(f"MISSED  {name}")
        else:
            caught += 1
            print(f"CAUGHT  {name}")

    print()
    print(f"Caught {caught} of {len(MUTANTS)} mutants")
    return 0 if caught == len(MUTANTS) else 1


if __name__ == "__main__":
    sys.exit(main())
