# selfcheck_scope.py
# Lab U01-04, Part 1 self-check. Run it from the folder that holds
# shift_counters.py and your scope_map.md:
#
#     python selfcheck_scope.py
#
# Do not edit this file.

import importlib
import os
import subprocess
import sys
from pathlib import Path

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

EXPECTED_REPORT = """First shift on Line 3: 3 starts
  L3-PRS-01: 360 strokes
  L3-PRS-02: 450 strokes
Second shift on Line 3: 0 starts
  L3-PRS-01: 0 strokes
  L3-PRS-02: 0 strokes"""

SCOPE_MAP_NAMES = ["SHIFT_NAMES", "current_shift", "line_name", "starts_this_shift",
                   "asset_tag", "strokes", "minutes", "presses", "press", "lines"]


def fresh_module():
    """Import shift_counters again, so every check starts from the file as written."""
    if "shift_counters" in sys.modules:
        return importlib.reload(sys.modules["shift_counters"])
    return importlib.import_module("shift_counters")


def s1_report():
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    result = subprocess.run([sys.executable, "shift_counters.py"], cwd=HERE, env=env,
                            capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        last = result.stderr.strip().splitlines()[-1] if result.stderr.strip() else "no message"
        return f"shift_counters.py crashed: {last}"
    got = result.stdout.strip().replace("\r\n", "\n")
    if got != EXPECTED_REPORT:
        return "the report does not match yet. It printed:\n        " + got.replace("\n", "\n        ")
    return None


def s2_class_counter():
    module = fresh_module()
    first, second = module.Press("L3-PRS-01"), module.Press("L3-PRS-02")
    first.start()
    second.start()
    first.start()
    if module.Press.starts_this_shift != 3:
        return f"after three starts, Press.starts_this_shift is {module.Press.starts_this_shift}; expected 3"
    for press in (first, second):
        if "starts_this_shift" in vars(press):
            return f"{press.asset_tag} has its own starts_this_shift, which hides the class count"
    return None


def s3_reset():
    module = fresh_module()
    press = module.Press("L3-PRS-01")
    press.run(30, 12)
    press.reset_for_new_shift()
    if press.strokes != 0:
        return f"after reset_for_new_shift(), strokes is {press.strokes}; expected 0"
    return None


def s4_change_shift():
    module = fresh_module()
    press = module.Press("L3-PRS-01")
    press.start()
    module.change_shift([press])
    if module.current_shift != "Second shift":
        return f"after change_shift(), the module's current_shift is {module.current_shift!r}; expected 'Second shift'"
    if module.Press.starts_this_shift != 0:
        return "after change_shift(), Press.starts_this_shift should be 0"
    return None


def s5_scope_map():
    path = HERE / "scope_map.md"
    if not path.is_file():
        return "scope_map.md is not in this folder yet (copy scope_map_template.md)"
    text = path.read_text(encoding="utf-8")
    missing = [name for name in SCOPE_MAP_NAMES if f"`{name}`" not in text]
    if missing:
        return f"scope_map.md has no row naming {', '.join(missing)} in backticks"
    if "TODO" in text:
        return "scope_map.md still contains TODO"
    return None


CHECKS = [
    ("S1 the report is right", s1_report),
    ("S2 starts are counted once, on the class", s2_class_counter),
    ("S3 a new shift zeroes each press", s3_reset),
    ("S4 change_shift changes the module's shift name", s4_change_shift),
    ("S5 scope_map.md names all ten names and has no TODO left", s5_scope_map),
]


def main():
    passed = 0
    for label, check in CHECKS:
        try:
            problem = check()
        except Exception as error:
            problem = f"crashed with {type(error).__name__}: {error}"
        if problem is None:
            passed += 1
            print(f"PASS  {label}")
        else:
            print(f"FAIL  {label}")
            print(f"      {problem}")
    print()
    print(f"{passed} of {len(CHECKS)} self-checks passed")
    return 0 if passed == len(CHECKS) else 1


if __name__ == "__main__":
    sys.exit(main())
