// ShiftData.cs
// Invented data for Lab U06-01. Riverside Fabrication is a composite: an
// invented shop. No real plant, person, or machine is described here.
//
// Do not edit this file. Your code goes in Program.cs.

namespace ShiftSummary;

internal static class ShiftData
{
    // The cure oven's target temperature, and how far it may drift either way
    // before a reading counts as out of tolerance.
    public const double SetpointC = 200.0;
    public const double ToleranceC = 10.0;

    // One oven reading per minute for the first 30 minutes of the shift.
    // Index 0 is minute 1.
    public static readonly double[] OvenTempsC =
    {
        196.5, 198.0, 199.2, 200.1, 200.4, 201.0, 200.8, 199.9, 200.3, 201.2,
        202.5, 204.0, 206.1, 208.3, 211.0, 213.4, 216.2, 218.9, 221.5, 219.8,
        217.0, 214.2, 211.6, 209.0, 206.4, 204.1, 202.2, 201.0, 200.2, 199.8,
    };

    // Press 1, for the whole shift.
    public const int ScheduledMinutes = 480;
    public const int RunMinutes = 437;
    public const int PartsMade = 1250;
    public const int PartsPerBox = 48;

    // The press controller's status word, exactly as the panel receives it.
    public const int StatusWord = 0x2C;
}
