# selfcheck_machine.py
# Lab U01-01 self-check. Run it from the folder that holds your machine.py:
#
#     python selfcheck_machine.py
#
# It builds Machine objects and checks each rule in the lab handout.
# Do not edit this file. Edit machine.py until every check passes.

import math
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

from machine import Machine  # noqa: E402


def make(tag="L3-PRS-01", name="Press 1", kw=15):
    return Machine(tag, name, kw)


def expect_error(error_type, action, label):
    """Run action. Return a problem message, or None if it raised error_type."""
    try:
        action()
    except error_type:
        return None
    except Exception as other:  # the wrong kind of refusal
        return f"{label} raised {type(other).__name__}, expected {error_type.__name__}"
    return f"{label} was accepted, expected {error_type.__name__}"


# Each check returns None when it passes, or a short message saying what is wrong.

def check_builds():
    press = make(name="  Press 1  ")
    if press.asset_tag != "L3-PRS-01" or press.name != "Press 1":
        return f"stored tag {press.asset_tag!r} and name {press.name!r}; expected 'L3-PRS-01' and 'Press 1' (trimmed)"
    if press.rated_kw != 15 or not isinstance(press.rated_kw, float):
        return f"rated_kw is {press.rated_kw!r}; expected 15.0, a float"
    return None


def check_bad_tags():
    for tag in ["", "   ", None, 301]:
        problem = expect_error(ValueError, lambda: make(tag=tag), f"asset tag {tag!r}")
        if problem:
            return problem
    return None


def check_bad_names():
    for name in ["", "   ", None]:
        problem = expect_error(ValueError, lambda: make(name=name), f"name {name!r}")
        if problem:
            return problem
    return None


def check_rating_type():
    for kw in ["15", True, None]:
        problem = expect_error(TypeError, lambda: make(kw=kw), f"rated_kw {kw!r}")
        if problem:
            return problem
    return None


def check_rating_range():
    for kw in [0, -5, 501, math.nan, math.inf]:
        problem = expect_error(ValueError, lambda: make(kw=kw), f"rated_kw {kw!r}")
        if problem:
            return problem
    if make(kw=500).rated_kw != 500.0:
        return "rated_kw 500 should be allowed; it is the maximum"
    return None


def check_start_stop():
    press = make()
    if press.is_running() is not False:
        return "a new machine should not be running"
    press.start()
    if press.is_running() is not True:
        return "after start(), is_running() should be True"
    press.stop()
    if press.is_running() is not False:
        return "after stop(), is_running() should be False"
    return None


def check_repr():
    text = repr(make(name="Press 1"))
    expected = "Machine(asset_tag='L3-PRS-01', name='Press 1', rated_kw=15.0)"
    if text != expected:
        return f"repr is {text!r}; expected {expected!r}"
    return None


def check_lockout_stops():
    press = make()
    press.start()
    press.lock_out("tech-07")
    if press.is_running():
        return "lock_out() must stop a running machine"
    if not press.is_locked_out() or press.locked_out_by() != "tech-07":
        return f"after lock_out('tech-07'): is_locked_out()={press.is_locked_out()!r}, locked_out_by()={press.locked_out_by()!r}"
    return None


def check_locked_cannot_start():
    press = make()
    press.lock_out("tech-07")
    problem = expect_error(RuntimeError, press.start, "start() while locked out")
    if problem:
        return problem
    if press.is_running():
        return "a locked-out machine is running after the refused start()"
    return None


def check_only_holder_releases():
    press = make()
    press.lock_out("tech-07")
    problem = expect_error(RuntimeError, lambda: press.release_lockout("tech-12"),
                           "release_lockout by a different badge")
    if problem:
        return problem
    if press.locked_out_by() != "tech-07":
        return "a refused release must leave the lock in place"
    press.release_lockout("tech-07")
    if press.is_locked_out() or press.locked_out_by() is not None:
        return "the holder's release should clear the lock"
    press.start()
    if not press.is_running():
        return "after the lock is released, start() should work"
    return None


def check_no_takeover():
    press = make()
    press.lock_out("tech-07")
    problem = expect_error(RuntimeError, lambda: press.lock_out("tech-12"),
                           "a second badge taking over the lock")
    if problem:
        return problem
    press.lock_out("tech-07")  # the same holder again is harmless
    if press.locked_out_by() != "tech-07":
        return "the lock should still belong to tech-07"
    return None


def check_bad_release_and_badge():
    press = make()
    problem = expect_error(RuntimeError, lambda: press.release_lockout("tech-07"),
                           "release_lockout on a machine nobody locked")
    if problem:
        return problem
    for badge in ["", "  ", None]:
        problem = expect_error(ValueError, lambda: press.lock_out(badge), f"lock_out({badge!r})")
        if problem:
            return problem
    if press.is_locked_out():
        return "a refused lock_out must not lock the machine"
    return None


def check_run_time():
    press = make()
    problem = expect_error(RuntimeError, lambda: press.record_run(10), "record_run on a stopped machine")
    if problem:
        return problem
    press.start()
    press.record_run(10)
    press.record_run(5)
    if press.run_minutes() != 15:
        return f"run_minutes() is {press.run_minutes()!r} after 10 and 5; expected 15"
    return None


def check_run_time_values():
    press = make()
    press.start()
    for minutes in [0, -3, 2.5, True, "10"]:
        problem = expect_error(ValueError, lambda: press.record_run(minutes), f"record_run({minutes!r})")
        if problem:
            return problem
    if press.run_minutes() != 0:
        return "refused values must not change run_minutes()"
    return None


def check_status_text():
    press = make()
    expected = "L3-PRS-01 Press 1: STOPPED, 0 min run"
    if press.status_text() != expected:
        return f"new machine: {press.status_text()!r}; expected {expected!r}"
    press.start()
    press.record_run(45)
    expected = "L3-PRS-01 Press 1: RUNNING, 45 min run"
    if press.status_text() != expected:
        return f"running: {press.status_text()!r}; expected {expected!r}"
    press.lock_out("tech-07")
    expected = "L3-PRS-01 Press 1: LOCKED OUT (tech-07), 45 min run"
    if press.status_text() != expected:
        return f"locked out: {press.status_text()!r}; expected {expected!r}"
    return None


def check_separate_objects():
    press1 = make("L3-PRS-01", "Press 1", 15)
    press2 = make("L3-PRS-02", "Press 2", 22)
    press1.start()
    press2.lock_out("tech-07")
    if press2.is_running() or press2.locked_out_by() != "tech-07":
        return "after press2.lock_out('tech-07'), press2 should be stopped and locked by tech-07"
    if not press1.is_running() or press1.is_locked_out():
        return "locking press2 changed press1: the two machines share state"
    return None


CHECKS = [
    (1, "01 builds, trims, and stores rated_kw as a float", check_builds),
    (1, "02 refuses a blank or non-string asset tag (ValueError)", check_bad_tags),
    (1, "03 refuses a blank or non-string name (ValueError)", check_bad_names),
    (1, "04 refuses a rated_kw that is not a number (TypeError)", check_rating_type),
    (1, "05 refuses a rated_kw outside above 0 to 500 (ValueError)", check_rating_range),
    (1, "06 start() and stop()", check_start_stop),
    (1, "07 __repr__", check_repr),
    (2, "08 lock_out() stops the machine and records the badge", check_lockout_stops),
    (2, "09 a locked-out machine refuses to start (RuntimeError)", check_locked_cannot_start),
    (2, "10 only the lock holder can release (RuntimeError)", check_only_holder_releases),
    (2, "11 a second badge cannot take over a lock (RuntimeError)", check_no_takeover),
    (2, "12 bad release and blank badge are refused", check_bad_release_and_badge),
    (2, "13 run time only accumulates while running", check_run_time),
    (2, "14 record_run refuses anything but a positive whole number", check_run_time_values),
    (2, "15 status_text() for stopped, running, and locked out", check_status_text),
    (2, "16 two machines never share state", check_separate_objects),
]


def main():
    passed = {1: 0, 2: 0}
    total = {1: 0, 2: 0}
    for part, label, check in CHECKS:
        total[part] += 1
        try:
            problem = check()
        except Exception as error:
            problem = f"crashed with {type(error).__name__}: {error}"
        if problem is None:
            passed[part] += 1
            print(f"PASS  {label}")
        else:
            print(f"FAIL  {label}")
            print(f"      {problem}")
    print()
    print(f"Part 1: {passed[1]} of {total[1]}    Part 2: {passed[2]} of {total[2]}")
    print(f"{passed[1] + passed[2]} of {total[1] + total[2]} self-checks passed")
    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
