# rogue_script.py
# Lab U01-03. Do not edit this file.
#
# Four lines somebody could add to any program that uses the Oven class.
# None of them calls a method. Each one tries to change the oven directly.
# Run it before Part 1 and after Part 1, and compare.
#
# Riverside Fabrication is a composite shop. Everything here is invented.
#
#     python rogue_script.py

import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

from oven import Oven  # noqa: E402

ATTEMPTS = [
    ("set the setpoint to 900 C on a 240 C oven", "setpoint_c", 900),
    ("turn the heat on while the door is open", "heating", True),
    ("type a word where a reading goes", "temperature_c", "hot"),
    ("repaint the asset tag", "asset_tag", "L3-OVN-99"),
]


def main():
    oven = Oven("L3-OVN-01", "Cure Oven", 200.0, 240.0)
    oven.open_door("tech-07")
    accepted = 0
    for number, (what, attribute, value) in enumerate(ATTEMPTS, start=1):
        try:
            setattr(oven, attribute, value)
        except (AttributeError, TypeError, ValueError) as error:
            print(f"{number}. {what}: refused ({type(error).__name__}: {error})")
        else:
            accepted += 1
            print(f"{number}. {what}: ACCEPTED")
    print()
    try:
        print(oven.status_text())
    except Exception as error:
        print(f"status_text() crashed: {type(error).__name__}: {error}")
    print(f"{accepted} of {len(ATTEMPTS)} rogue lines were accepted")


if __name__ == "__main__":
    main()
