# selfcheck_oven.py
# Lab U01-03 self-check. Run it from the folder that holds your oven.py:
#
#     python selfcheck_oven.py part1      Monday: underscores and properties
#     python selfcheck_oven.py part2      Tuesday: static and class methods
#     python selfcheck_oven.py            both parts
#
# Do not edit this file. Edit oven.py until every check passes.

import math
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

from oven import Oven  # noqa: E402


def make(tag="L3-OVN-01", name="Cure Oven", setpoint=200.0, max_c=240.0):
    return Oven(tag, name, setpoint, max_c)


def expect_error(error_type, action, label):
    try:
        action()
    except error_type:
        return None
    except Exception as other:
        return f"{label} raised {type(other).__name__}, expected {error_type.__name__}"
    return f"{label} was accepted, expected {error_type.__name__}"


def first_problem(*problems):
    for problem in problems:
        if problem:
            return problem
    return None


# ----- Part 1 -----

def p1_builds():
    oven = make(name="  Cure Oven ")
    got = (oven.asset_tag, oven.name, oven.setpoint_c, oven.max_c, oven.temperature_c,
           oven.heating, oven.door_open, oven.last_opened_by)
    expected = ("L3-OVN-01", "Cure Oven", 200.0, 240.0, None, False, False, None)
    if got != expected:
        return f"a new oven reads {got}; expected {expected}"
    if not isinstance(make(setpoint=200, max_c=240).setpoint_c, float):
        return "setpoint_c should be stored as a float"
    return None


def p1_read_only():
    oven = make()
    for attribute, value in [("asset_tag", "L3-OVN-99"), ("name", "Other"), ("max_c", 900.0),
                             ("temperature_c", 20.0), ("heating", True), ("door_open", True),
                             ("last_opened_by", "anyone")]:
        problem = expect_error(AttributeError, lambda: setattr(oven, attribute, value),
                               f"oven.{attribute} = {value!r}")
        if problem:
            return problem
    return None


def p1_setpoint():
    oven = make()
    for value in ["200", True, None]:
        problem = expect_error(TypeError, lambda: setattr(oven, "setpoint_c", value), f"setpoint_c = {value!r}")
        if problem:
            return problem
    for value in [0, -5, 240.5, 900, math.nan, math.inf]:
        problem = expect_error(ValueError, lambda: setattr(oven, "setpoint_c", value), f"setpoint_c = {value!r}")
        if problem:
            return problem
    if oven.setpoint_c != 200.0:
        return "a refused setpoint must leave the old setpoint in place"
    oven.setpoint_c = 240
    if oven.setpoint_c != 240.0 or not isinstance(oven.setpoint_c, float):
        return "setpoint_c = 240 on a 240 C oven should be accepted and stored as 240.0"
    return None


def p1_construction_checked():
    return first_problem(
        expect_error(ValueError, lambda: make(setpoint=300.0), "a new oven with setpoint 300 and max 240"),
        expect_error(ValueError, lambda: make(setpoint=math.nan), "a new oven with setpoint nan"),
        expect_error(TypeError, lambda: make(setpoint="hot"), "a new oven with setpoint 'hot'"),
        expect_error(TypeError, lambda: make(max_c="240"), "a new oven with max_c '240'"),
        expect_error(ValueError, lambda: make(max_c=0), "a new oven with max_c 0"),
        expect_error(ValueError, lambda: make(max_c=401.0), "a new oven with max_c 401"),
        expect_error(ValueError, lambda: make(max_c=math.inf), "a new oven with max_c inf"),
        expect_error(ValueError, lambda: make(tag=""), "a new oven with a blank tag"),
        expect_error(ValueError, lambda: make(name="  "), "a new oven with a blank name"),
    )


def p1_temperature():
    oven = make()
    oven.record_temperature(185.5)
    if oven.temperature_c != 185.5:
        return "record_temperature(185.5) should store 185.5"
    for value in ["hot", True, None]:
        problem = expect_error(TypeError, lambda: oven.record_temperature(value), f"record_temperature({value!r})")
        if problem:
            return problem
    for value in [-41, 1201, math.nan, -math.inf]:
        problem = expect_error(ValueError, lambda: oven.record_temperature(value), f"record_temperature({value!r})")
        if problem:
            return problem
    if oven.temperature_c != 185.5:
        return "a refused reading must leave the last good reading in place"
    return None


def p1_door_rules():
    oven = make()
    oven.start_heating()
    if not oven.heating:
        return "start_heating() with the door closed should heat"
    oven.open_door("tech-07")
    if oven.heating or not oven.door_open or oven.last_opened_by != "tech-07":
        return "open_door('tech-07') should stop the heat, open the door, and record tech-07"
    problem = expect_error(RuntimeError, oven.start_heating, "start_heating() with the door open")
    if problem:
        return problem
    if oven.heating:
        return "a refused start_heating() must leave the heat off"
    oven.close_door()
    oven.start_heating()
    if not oven.heating:
        return "after close_door(), start_heating() should work"
    problem = expect_error(ValueError, lambda: oven.open_door("  "), "open_door('  ')")
    if problem:
        return problem
    if oven.door_open or not oven.heating:
        return "a refused open_door() must change nothing"
    return None


def p1_status_and_repr():
    oven = make()
    checks = [("IDLE", "L3-OVN-01 Cure Oven: IDLE, setpoint 200 C, no reading")]
    if oven.status_text() != checks[0][1]:
        return f"new oven: {oven.status_text()!r}; expected {checks[0][1]!r}"
    oven.start_heating()
    oven.record_temperature(185.5)
    expected = "L3-OVN-01 Cure Oven: HEATING, setpoint 200 C, reads 185.5 C"
    if oven.status_text() != expected:
        return f"heating: {oven.status_text()!r}; expected {expected!r}"
    oven.open_door("tech-07")
    expected = "L3-OVN-01 Cure Oven: DOOR OPEN (tech-07), setpoint 200 C, reads 185.5 C"
    if oven.status_text() != expected:
        return f"door open: {oven.status_text()!r}; expected {expected!r}"
    expected = "Oven(asset_tag='L3-OVN-01', name='Cure Oven', setpoint_c=200.0, max_c=240.0)"
    if repr(oven) != expected:
        return f"repr is {repr(oven)!r}; expected {expected!r}"
    return None


def p1_internal_names():
    oven = make()
    oven.open_door("tech-07")
    names = sorted(vars(oven))
    public = [name for name in names if not name.startswith("_")]
    if public:
        return f"these instance attributes have no underscore: {public}"
    if "_Oven__last_opened_by" not in names:
        return f"the badge should be stored in a two-underscore attribute, __last_opened_by; found {names}"
    return None


def p1_separate():
    first, second = make(), make(tag="L3-OVN-02", name="Paint Oven", setpoint=180.0, max_c=220.0)
    first.open_door("tech-07")
    first.setpoint_c = 150
    if second.door_open or second.last_opened_by is not None or second.setpoint_c != 180.0:
        return "changing one oven changed another: the ovens share state"
    return None


# ----- Part 2 -----

def p2_static():
    raw = Oven.__dict__.get("is_valid_asset_tag")
    if not isinstance(raw, staticmethod):
        return "is_valid_asset_tag should be a @staticmethod on Oven"
    for tag, expected in [("L3-OVN-01", True), ("L3-PRS-12", True), ("l3-ovn-01", False),
                          ("L3-OVN-1", False), ("L3-OVN-01\n", False), (" L3-OVN-01", False),
                          ("L3-OVN-٠١", False), ("", False), (None, False), (301, False)]:
        if Oven.is_valid_asset_tag(tag) is not expected:
            return f"is_valid_asset_tag({tag!r}) should be {expected}"
    if make().is_valid_asset_tag("L3-OVN-01") is not True:
        return "is_valid_asset_tag should also work when called on an oven"
    return None


def p2_constructor_uses_it():
    for tag in ["OVEN-1", "l3-ovn-01", "L3-OVN-01 "]:
        problem = expect_error(ValueError, lambda: make(tag=tag), f"a new oven tagged {tag!r}")
        if problem:
            return problem
    return None


def p2_counter():
    raw = Oven.__dict__.get("ovens_created")
    if not isinstance(raw, classmethod):
        return "ovens_created should be a @classmethod on Oven"
    before = Oven.ovens_created()
    make()
    make(tag="L3-OVN-02")
    try:
        make(setpoint=900.0)
    except ValueError:
        pass
    after = Oven.ovens_created()
    if after != before + 2:
        return f"two good ovens and one refused oven changed the count by {after - before}; expected 2"
    if "_ovens_created" in vars(make()):
        return "the count is being stored on an oven; it belongs to the class"
    return None


def p2_from_record():
    raw = Oven.__dict__.get("from_record")
    if not isinstance(raw, classmethod):
        return "from_record should be a @classmethod on Oven"
    row = {"asset_tag": " l3-ovn-02 ", "name": " Paint Oven ", "setpoint_c": "180", "max_c": "220.0"}
    oven = Oven.from_record(row)
    if type(oven) is not Oven:
        return f"from_record returned a {type(oven).__name__}; expected an Oven"
    expected = "Oven(asset_tag='L3-OVN-02', name='Paint Oven', setpoint_c=180.0, max_c=220.0)"
    if repr(oven) != expected:
        return f"from_record built {repr(oven)!r}; expected {expected!r}"
    return first_problem(
        expect_error(ValueError, lambda: Oven.from_record({"asset_tag": "L3-OVN-02", "name": "Paint Oven",
                                                           "max_c": "220"}), "a record with no setpoint_c"),
        expect_error(ValueError, lambda: Oven.from_record(dict(row, setpoint_c="hot")), "a record with setpoint_c 'hot'"),
        expect_error(ValueError, lambda: Oven.from_record(dict(row, setpoint_c="300")), "a record with setpoint_c '300'"),
        expect_error(ValueError, lambda: Oven.from_record(dict(row, asset_tag="OVEN 2")), "a record tagged 'OVEN 2'"),
    )


PART1 = [
    ("P1-1 a new oven reads correctly through its properties", p1_builds),
    ("P1-2 seven properties are read-only (AttributeError)", p1_read_only),
    ("P1-3 setpoint_c refuses bad values and keeps the old one", p1_setpoint),
    ("P1-4 construction runs the same checks", p1_construction_checked),
    ("P1-5 record_temperature refuses impossible readings", p1_temperature),
    ("P1-6 the door and the heat follow the rules", p1_door_rules),
    ("P1-7 status_text and __repr__", p1_status_and_repr),
    ("P1-8 every instance attribute is internal, and the badge is name-mangled", p1_internal_names),
    ("P1-9 two ovens never share state", p1_separate),
]
PART2 = [
    ("P2-1 is_valid_asset_tag is a static method with the right answers", p2_static),
    ("P2-2 the constructor refuses a bad tag", p2_constructor_uses_it),
    ("P2-3 ovens_created is a class method that counts good ovens only", p2_counter),
    ("P2-4 from_record builds an oven from spreadsheet text", p2_from_record),
]


def run(checks):
    passed = 0
    for label, check in checks:
        try:
            problem = check()
        except Exception as error:
            problem = f"crashed with {type(error).__name__}: {error}"
        if problem is None:
            passed += 1
            print(f"PASS  {label}")
        else:
            print(f"FAIL  {label}")
            print(f"      {problem}")
    return passed


def main():
    choice = sys.argv[1] if len(sys.argv) > 1 else "all"
    if choice not in ("part1", "part2", "all"):
        print("Usage: python selfcheck_oven.py [part1 | part2]")
        return 2
    checks = {"part1": PART1, "part2": PART2, "all": PART1 + PART2}[choice]
    passed = run(checks)
    print()
    print(f"{passed} of {len(checks)} self-checks passed")
    return 0 if passed == len(checks) else 1


if __name__ == "__main__":
    sys.exit(main())
