# selfcheck_crib.py
# Lab U01-02 self-check. Run it from the folder that holds your tool_crib.py:
#
#     python selfcheck_crib.py part2      Wednesday: Tool and the two functions
#     python selfcheck_crib.py part3      Thursday: ToolCrib
#     python selfcheck_crib.py            both parts
#
# Do not edit this file. Edit tool_crib.py until every check passes.

import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

import tool_crib  # noqa: E402


def need(name):
    """Return a name from tool_crib.py, or raise a clear message if it is missing."""
    if not hasattr(tool_crib, name):
        raise LookupError(f"tool_crib.py has no {name} yet")
    return getattr(tool_crib, name)


def expect_error(error_type, action, label):
    try:
        action()
    except error_type:
        return None
    except LookupError:
        raise
    except Exception as other:
        return f"{label} raised {type(other).__name__}, expected {error_type.__name__}"
    return f"{label} was accepted, expected {error_type.__name__}"


def first_problem(*problems):
    for problem in problems:
        if problem:
            return problem
    return None


# ----- Part 2 -----

def p2_functions():
    minutes_between = need("minutes_between")
    format_duration = need("format_duration")
    Tool = need("Tool")
    for name in ["minutes_between", "format_duration"]:
        if name in vars(Tool):
            return f"{name} is inside Tool; it needs no tool, so it stays a function"
    if minutes_between(30, 150) != 120:
        return f"minutes_between(30, 150) is {minutes_between(30, 150)!r}; expected 120"
    for minutes, text in [(65, "1 h 05 min"), (0, "0 h 00 min"), (270, "4 h 30 min")]:
        if format_duration(minutes) != text:
            return f"format_duration({minutes}) is {format_duration(minutes)!r}; expected {text!r}"
    return None


def p2_builds():
    Tool = need("Tool")
    tool = Tool("TC-014", "  Torque wrench ")
    if getattr(tool, "tag", None) != "TC-014" or getattr(tool, "name", None) != "Torque wrench":
        return "Tool('TC-014', '  Torque wrench ') should store tag 'TC-014' and the trimmed name"
    expected = "Tool(tag='TC-014', name='Torque wrench')"
    if repr(tool) != expected:
        return f"repr is {repr(tool)!r}; expected {expected!r}"
    return None


def p2_bad_arguments():
    Tool = need("Tool")
    for tag in ["TC-14", "tc-014", "TC-0140", " TC-014", "TC-01٤", None, 14]:
        problem = expect_error(ValueError, lambda: Tool(tag, "Wrench"), f"tag {tag!r}")
        if problem:
            return problem
    for name in ["", "   ", None]:
        problem = expect_error(ValueError, lambda: Tool("TC-014", name), f"name {name!r}")
        if problem:
            return problem
    return None


def p2_check_out():
    tool = need("Tool")("TC-014", "Torque wrench")
    if tool.is_out() or tool.holder() is not None:
        return "a new tool should be in the crib with no holder"
    tool.check_out("tech-07", 30)
    if not tool.is_out() or tool.holder() != "tech-07":
        return f"after check_out('tech-07', 30): is_out()={tool.is_out()!r}, holder()={tool.holder()!r}"
    problem = expect_error(RuntimeError, lambda: tool.check_out("tech-12", 40), "a second check_out")
    return first_problem(problem, None if tool.holder() == "tech-07" else "a refused check_out changed the holder")


def p2_check_out_values():
    tool = need("Tool")("TC-014", "Torque wrench")
    for badge in ["", "  ", None]:
        problem = expect_error(ValueError, lambda: tool.check_out(badge, 30), f"check_out({badge!r}, 30)")
        if problem:
            return problem
    for minute in [-1, 2.5, True, "30", None]:
        problem = expect_error(ValueError, lambda: tool.check_out("tech-07", minute), f"check_out('tech-07', {minute!r})")
        if problem:
            return problem
    if tool.is_out():
        return "a refused check_out must leave the tool in the crib"
    return None


def p2_check_in():
    tool = need("Tool")("TC-022", "Digital caliper")
    problem = expect_error(RuntimeError, lambda: tool.check_in(150), "check_in on a tool that is in the crib")
    if problem:
        return problem
    tool.check_out("tech-12", 95)
    problem = expect_error(ValueError, lambda: tool.check_in(90), "check_in at minute 90 for a tool out at 95")
    if problem:
        return problem
    if not tool.is_out():
        return "a refused check_in must leave the tool out"
    minutes = tool.check_in(150)
    if minutes != 55:
        return f"check_in(150) returned {minutes!r}; expected 55"
    if tool.is_out() or tool.holder() is not None:
        return "after check_in the tool should be in with no holder"
    return None


def p2_overdue():
    tool = need("Tool")("TC-014", "Torque wrench")
    if tool.minutes_out(100) is not None or tool.is_overdue(100) is not False:
        return "a tool in the crib: minutes_out() should be None and is_overdue() False"
    tool.check_out("tech-07", 30)
    if tool.minutes_out(270) != 240 or tool.is_overdue(270) is not False:
        return "out at 30, checked at 270: 240 minutes, and exactly 240 is not overdue"
    if tool.is_overdue(271) is not True:
        return "out at 30, checked at 271: 241 minutes is overdue"
    return None


def p2_status_text():
    tool = need("Tool")("TC-014", "Torque wrench")
    cases = [(300, "TC-014 Torque wrench: in the crib")]
    for now, expected in cases:
        if tool.status_text(now) != expected:
            return f"status_text({now}) is {tool.status_text(now)!r}; expected {expected!r}"
    tool.check_out("tech-07", 30)
    for now, expected in [(95, "TC-014 Torque wrench: out to tech-07 for 1 h 05 min"),
                          (300, "TC-014 Torque wrench: out to tech-07 for 4 h 30 min OVERDUE")]:
        if tool.status_text(now) != expected:
            return f"status_text({now}) is {tool.status_text(now)!r}; expected {expected!r}"
    return None


def p2_separate():
    Tool = need("Tool")
    wrench, caliper = Tool("TC-014", "Torque wrench"), Tool("TC-022", "Digital caliper")
    wrench.check_out("tech-07", 30)
    if caliper.is_out():
        return "checking out one tool checked out another: the tools share state"
    return None


# ----- Part 3 -----

def make_crib():
    Tool, ToolCrib = need("Tool"), need("ToolCrib")
    crib = ToolCrib("Line 3 crib")
    for tag, name in [("TC-014", "Torque wrench"), ("TC-022", "Digital caliper"), ("TC-031", "Feeler gauge set")]:
        crib.add(Tool(tag, name))
    return crib


def p3_builds():
    ToolCrib = need("ToolCrib")
    crib = ToolCrib("  Line 3 crib ")
    if getattr(crib, "name", None) != "Line 3 crib":
        return "ToolCrib('  Line 3 crib ') should store the trimmed name"
    expected = "ToolCrib(name='Line 3 crib', tools=0)"
    if repr(crib) != expected:
        return f"repr is {repr(crib)!r}; expected {expected!r}"
    for name in ["", "  ", None]:
        problem = expect_error(ValueError, lambda: ToolCrib(name), f"crib name {name!r}")
        if problem:
            return problem
    return None


def p3_add_and_find():
    Tool, ToolCrib = need("Tool"), need("ToolCrib")
    crib = ToolCrib("Line 3 crib")
    wrench = Tool("TC-014", "Torque wrench")
    if crib.add(wrench) is not wrench:
        return "add() should return the tool it added"
    if len(crib) != 1 or "TC-014" not in crib or "TC-099" in crib:
        return "after one add: len should be 1, 'TC-014' in crib True, 'TC-099' in crib False"
    if crib.get("TC-014") is not wrench or crib.get("TC-099") is not None:
        return "get() should return the same Tool object, or None for an unknown tag"
    return None


def p3_refuses():
    Tool = need("Tool")
    crib = make_crib()
    original = crib.get("TC-014")
    problem = first_problem(
        expect_error(TypeError, lambda: crib.add("TC-040"), "add('TC-040')"),
        expect_error(ValueError, lambda: crib.add(Tool("TC-014", "Spare wrench")), "a second TC-014"),
    )
    if problem:
        return problem
    if len(crib) != 3 or crib.get("TC-014") is not original:
        return "a refused add must leave the crib exactly as it was"
    return None


def p3_tools_copy():
    crib = make_crib()
    tools = crib.tools()
    if not isinstance(tools, tuple):
        return f"tools() returned a {type(tools).__name__}; expected a tuple copy"
    if [tool.tag for tool in tools] != ["TC-014", "TC-022", "TC-031"]:
        return "tools() should list tools in the order they were added"
    return None


def p3_delegates():
    crib = make_crib()
    crib.check_out("TC-014", "tech-07", 30)
    if not crib.get("TC-014").is_out():
        return "crib.check_out('TC-014', ...) should check out that tool"
    problem = expect_error(RuntimeError, lambda: crib.check_out("TC-014", "tech-12", 40), "checking out a tool that is out")
    if problem:
        return problem
    if crib.check_in("TC-014", 90) != 60:
        return "crib.check_in('TC-014', 90) should return 60"
    return first_problem(
        expect_error(KeyError, lambda: crib.check_out("TC-099", "tech-07", 30), "check_out of unknown TC-099"),
        expect_error(KeyError, lambda: crib.check_in("TC-099", 30), "check_in of unknown TC-099"),
        expect_error(RuntimeError, lambda: crib.check_in("TC-031", 310), "check_in of TC-031, which is in the crib"),
    )


def p3_out_and_overdue():
    crib = make_crib()
    crib.check_out("TC-014", "tech-07", 30)
    crib.check_out("TC-031", "tech-12", 200)
    out = [tool.tag for tool in crib.out_tools()]
    late = [tool.tag for tool in crib.overdue(300)]
    if out != ["TC-014", "TC-031"]:
        return f"out_tools() tags are {out}; expected ['TC-014', 'TC-031']"
    if late != ["TC-014"]:
        return f"overdue(300) tags are {late}; expected ['TC-014']"
    return None


def p3_report():
    crib = make_crib()
    crib.check_out("TC-014", "tech-07", 30)
    expected = [
        "TC-014 Torque wrench: out to tech-07 for 4 h 30 min OVERDUE",
        "TC-022 Digital caliper: in the crib",
        "TC-031 Feeler gauge set: in the crib",
    ]
    if crib.report(300) != expected:
        return f"report(300) is {crib.report(300)!r}"
    return None


def p3_iteration():
    Tool = need("Tool")
    crib = make_crib()
    seen = []
    for tool in crib:
        seen.append(tool.tag)
        if tool.tag == "TC-014":
            crib.add(Tool("TC-040", "Dial indicator"))  # adding while looping must not break the loop
    if seen != ["TC-014", "TC-022", "TC-031"]:
        return f"looping over the crib gave {seen}; expected the three tools in order"
    if len(crib) != 4:
        return "the tool added during the loop should be in the crib afterwards"
    return None


def p3_separate():
    Tool, ToolCrib = need("Tool"), need("ToolCrib")
    day, night = ToolCrib("Day crib"), ToolCrib("Night crib")
    day.add(Tool("TC-014", "Torque wrench"))
    if len(night) != 0 or "TC-014" in night:
        return "adding to one crib changed another: the cribs share a collection"
    return None


PART2 = [
    ("P2-1 minutes_between and format_duration stay functions", p2_functions),
    ("P2-2 Tool builds, trims, and has a __repr__", p2_builds),
    ("P2-3 Tool refuses a bad tag or blank name (ValueError)", p2_bad_arguments),
    ("P2-4 check_out records the holder and refuses a second checkout", p2_check_out),
    ("P2-5 check_out refuses a blank badge or a bad minute (ValueError)", p2_check_out_values),
    ("P2-6 check_in returns minutes out and refuses bad calls", p2_check_in),
    ("P2-7 minutes_out and is_overdue", p2_overdue),
    ("P2-8 status_text for in, out, and overdue", p2_status_text),
    ("P2-9 two tools never share state", p2_separate),
]
PART3 = [
    ("P3-1 ToolCrib builds, trims, refuses a blank name, and has a __repr__", p3_builds),
    ("P3-2 add, len, in, and get", p3_add_and_find),
    ("P3-3 add refuses a non-Tool and a duplicate tag", p3_refuses),
    ("P3-4 tools() is a tuple copy in the order added", p3_tools_copy),
    ("P3-5 the crib finds the tool and the tool enforces its rules", p3_delegates),
    ("P3-6 out_tools and overdue", p3_out_and_overdue),
    ("P3-7 report lines in shelf order", p3_report),
    ("P3-8 looping over the crib, even while adding", p3_iteration),
    ("P3-9 two cribs never share tools", p3_separate),
]


def run(checks):
    passed = 0
    for label, check in checks:
        try:
            problem = check()
        except LookupError as missing:
            problem = str(missing).strip("'\"")
        except Exception as error:
            problem = f"crashed with {type(error).__name__}: {error}"
        if problem is None:
            passed += 1
            print(f"PASS  {label}")
        else:
            print(f"FAIL  {label}")
            print(f"      {problem}")
    return passed


def main():
    choice = sys.argv[1] if len(sys.argv) > 1 else "all"
    if choice not in ("part2", "part3", "all"):
        print("Usage: python selfcheck_crib.py [part2 | part3]")
        return 2
    checks = {"part2": PART2, "part3": PART3, "all": PART2 + PART3}[choice]
    passed = run(checks)
    print()
    print(f"{passed} of {len(checks)} self-checks passed")
    return 0 if passed == len(checks) else 1


if __name__ == "__main__":
    sys.exit(main())
